### ISSUE TITLE
Fix Scala doc warning.

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko#1048]
Motivation:
When compiling/pacakging with Java 21, I saw many doc warning.

>sbt publishLocal
![image](https://github.com/apache/incubator-pekko/assets/501740/de2daffe-83ef-4701-8c4c-b44e03b12cb1)

**Comment by mdedetrich** [comment]
So I am not sure if this is an issue worth leaving open because its even stated in documentation that if you are packaging/publishing Pekko, that you should only use JDK 11 + `export JAVA_8_HOME`.

Until we fix a lot of the workarounds in Pekko, it will likely never support being able to generically be packaged under any JDK especially considering that some packages such as sbt-paradox [only work on specific JDK's](https://github.com/apache/incubator-pekko/blob/639d5ad8ee48a8ac5c151df6370af426dd1b3c07/project/plugins.sbt#L33-L34)

**Comment by He-Pin** [comment]
I have `JAVA_8_HOME`, otherwise it will not compile, this seems an api mapping issue, but better done when we delete all the obsoleted code.

**Comment by mdedetrich** [comment]
> I have `JAVA_8_HOME`, otherwise it will not compile, this seems an api mapping issue, but better done when we delete all the obsoleted code.

Its not just an API missing issue, the version of sbt-paradox that we are using to build the docs will **_only_** run on JDK 8/11 because it uses unsafe. There are actually lots of reasons why we have to build Pekko in the way that its currently done.

My point is that if you have an expectation that this project can be built with any JDK, thats not going to happen anytime soon.

**Comment by pjfanning** [comment]
closing in favour of https://github.com/apache/incubator-pekko/issues/353
