### ISSUE TITLE
rename modules to replace 'akka' with 'pekko'

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#21]
aim is that all the `akka-*` jars will become `pekko-*` jars

**Comment by spangaer** [comment]
Could I argue that the "commands" used to make these changes,  that result in "massive commits", should be checked in as a script in a commit before the actual rename, so that:

1. The script can be reviewed instead of the change
2. The script can be applied to check that the rename commit result matches the script execution

**Comment by mdedetrich** [comment]
@pjfanning Since https://github.com/apache/incubator-pekko/pull/20 is abandoned, are you going to recreate it or should I? I was also thinking of rather than renaming the modules from `akka-*` to `pekko-*` (i.e. `akka-actor` to `pekko-actor`) that instead we should just have the module name without `pekko` (i.e. `akka-actor` would just become `actor`).

The reasoning is the same as renaming `akka-docs` to just `docs`, i.e. its extra/unneeded noise and its also not consistent with the other pekko repo's (i.e. alpakka doesn't have `akka-` prefix for each of their sbt modules). Since we are renaming the sbt modules anyways there isn't going to be any extra noise, only thing we need to do is to make sure to add the `pekko-` prefix in the generated jar which is quite easy.

**Comment by pjfanning** [comment]
> @pjfanning Since #20 is abandoned, are you going to recreate it or should I? I was also thinking of rather than renaming the modules from `akka-*` to `pekko-*` (i.e. `akka-actor` to `pekko-actor`) that instead we should just have the module name without `pekko` (i.e. `akka-actor` would just become `actor`).
> 
> The reasoning is the same as renaming `akka-docs` to just `docs`, i.e. its extra/unneeded noise and its also not consistent with the other pekko repo's (i.e. alpakka doesn't have `akka-` prefix for each of their sbt modules). Since we are renaming the sbt modules anyways there isn't going to be any extra noise, only thing we need to do is to make sure to add the `pekko-` prefix in the generated jar which is quite easy.
> 
> Should also do this after #35 gets merged so as to not deal with a lot of merge conflicts.

I'd prefer to keep the dir names for the modules to match the jar names. And I think the jar names should be like 'pekko-actor', etc.

**Comment by mdedetrich** [comment]
> I'd prefer to keep the dir names for the modules to match the jar names.

Right, but this is only the case for core akka, every other akka repo does not follow in this. In fact arguably from what I have seen in standard OS SBT projects, this isn't really idiomatic either.

> And I think the jar names should be like 'pekko-actor', etc.

This would be unchanged even with my suggestion, in fact its very easy to do this with SBT.

Would you be more open if I created a PR demonstrating this? Its actually not that hard.

**Comment by pjfanning** [comment]
sure, try it out

**Comment by spangaer** [comment]
I guess this is what #71 is about.

**Comment by pjfanning** [comment]
#71 is merged
