### ISSUE TITLE
detailed build instructions

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#335]
As part of Pekko release, we will need the Apache Incubator PMC to vote on our source release. They will need to be able to take the source release and to build Pekko jars using it.

There is an inadequate initial stab at:

https://github.com/apache/incubator-pekko/blob/main/README.md#building-from-source

We need to also spell out that you probably need to have 2 Java Runtimes installed. See #333 for background (and https://lists.apache.org/thread/zz77bc6tjhdp68cojj6vksrmlqqvn7ln)

We probably also want to make the instructions usable by Linux and Windows users.

**Comment by mdedetrich** [comment]
So we should also probably make a clear distinction between "building/compiling" and "making a release". The reason I am pointing this out is that you can compile/build the project fine on JDK 8 (I only have a single visible JDK installed, JDK 8 which is pointed to Pekko via [jenv](https://github.com/jenv/jenv)), it just won't have the optional JDK 11 features. This will also become important when inlining, i.e. https://github.com/apache/incubator-pekko/pull/305 because since inlining doesn't work with Scala's incremental compilation, you only want to enable it when doing a release build and not during development.

**Comment by pjfanning** [comment]
what's at https://github.com/apache/incubator-pekko/blob/main/README.md#building-from-source will do
