### ISSUE TITLE
possible need to include scala-java8-compat in LICENSE/NOTICE

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#362]
Some recent refactors have seen us make scala-java8-compat a dependency for Scala 2.12 only.

We need to analyse whether any code was copied into Pekko from scala-java8-compat and update our LICENSE and NOTICE files accordingly.

* https://github.com/apache/incubator-pekko/blob/main/LICENSE
* https://github.com/apache/incubator-pekko/blob/main/NOTICE

@mdedetrich could you confirm if this is needed - I can do a PR if one is needed

It is possible that we need to update other LICENSE/NOTICE files due to similar refactors in other pekko repos too.

**Comment by mdedetrich** [comment]
I'll check this properly tomorrow

**Comment by pjfanning** [comment]
@mdedetrich will you time to do this today? This is an important item to get squared off.

**Comment by mdedetrich** [comment]
Okay so I had a proper look into this including other converter functions which are not explicitly mentioned in this issue (I think its useful to tackle this properly at once)

* `FutureConverters`: This shouldn't require any adjustment to `LICENSE`/`NOTICE`/headers because there is no copied code, its just a wrapper that forwards function calls to the actual implementation which is a standard jar dependency
* `OptionConverters`: This is the same as `FutureConverters` but there is one "technically" correct exception which is https://github.com/apache/incubator-pekko/blob/898c69701b7783e6da9e69321ca345ea98ddc86b/actor/src/main/scala-2.12/org/apache/pekko/util/OptionConverters.scala#L28-L37. The reason why I state this is "technically" correct is that while its true that the code is the same (not exactly lexically but the compiled meaning of the code is the same) its basically impossible to come up with an alternative implementation since its so trivial (to drive this point further, this is about as trivial as asking someone how to add two numbers, 99% of people would write it as `a + b`). IANAL statement here, I am not going to make a call whether we should make a legal understanding of this, I just want to be clear about how benign/trivial the code is.
* `FunctionConverters`: Same as `FutureConverters`, its just forwarder functions, i.e. no copying of code.
* `ccompat` ergo collection compat: This is the one area where code was literally copied from `scala-collections-compat`. I guess that due to this we should should also copy the header over (i.e. https://github.com/scala/scala-collection-compat/blob/main/compat/src/main/scala-2.11_2.12/scala/collection/compat/BuildFrom.scala#L1-L11) and mention it in `LICENSE`/`NOTICE`.

@pjfanning Let me know if this answers your questions

**Comment by pjfanning** [comment]
thanks @mdedetrich - I think we can close this and not make any changes to the licenses

**Comment by justinmclean** [comment]
Given code was copied from a ALv2 licensed 3rd party and it has a NOTICE file that would impact our LICENSE and NOTICE file. I think that doing nothing is not the right choice here.

**Comment by pjfanning** [comment]
@justinmclean in the end no code was copied from the scala-java8-compat library - the Pekko code was refactored to not need that scala-java8-compat library but that did not involve taking any code from that library

**Comment by justinmclean** [comment]
"ergo collection compat: This is the one area where code was literally copied from scala-collections-compat"

**Comment by mdedetrich** [comment]
Shall this be closed?
