### ISSUE TITLE
Undefined behavior of PekkoPduProtobufCodec$

### ISSUE THREAD

**Issue by nicolasstucki** [apache/incubator-pekko#491]
The Scala spec states that names in the source should not contain $. These are reserved for code generation. Using a name with a $ will have undefined behavior.

https://github.com/apache/incubator-pekko/blob/fbac70e9dd57050449b6d00b7b9c6a2669d600d3/remote/src/main/scala/org/apache/pekko/remote/transport/PekkoPduCodec.scala#L131

A change in this undefined behavior was found in https://github.com/lampepfl/dotty/issues/18227

Solution: change the name of this object.

**Comment by pjfanning** [comment]
@mdedetrich any idea why the $ was added? It was added during one of your commits when we were renaming the akka packages. The Akka 2.6 code does not have a $ in the equivalent name.

**Comment by mdedetrich** [comment]
This was likely a mistake, @nicolasstucki does that mean we should make a new release?

**Comment by pjfanning** [comment]
we can start by release noting that this affects users of Scala 3.3.2 (which is only in preview)

**Comment by mdedetrich** [comment]
> * we can start by release noting that this affects users of Scala 3.3.2 (which is only in preview)
> * still works with Scala 3.3.1-RC4 as per @nicolasstucki
> * we should release Pekko 1.0.1 but we may not need to start the RC process yet
> * we may still be better off starting Pekko HTTP 1.0.0 release process first

So just to clarify (and @nicolasstucki can either confirm or deny this), but afaik this issue of using `$` in class names is not Scala 3 specific, its just that because incubator-pekko got added to Scala 3 integration testing (i.e. open community build) where it got revealed but its a general Scala isssue.

The core problem is that Scala (regardless if its Scala 2 or Scala 3) you should never have a `$` in class names that you define because Scala compiler itself will generate classes internally which can contain the `$`.

For this reason I would recommend making a new release irrespective of Scala 3, we still need to go through the release process. If possible Scala 2/3 should also add checks/warnings to prevent this in the future.

**Comment by pjfanning** [comment]
> i think this is not a bug of pekko but a scala3 regression.

Scala 3 is not likely to be changed to allow us not to fix the class name.

I'm happy to change this package private class name since the Scala spec says we shouldn't have $ suffix in class names.

**Comment by He-Pin** [comment]
@mdedetrich So why the compiler did not prevent this but produced an artifact?

**Comment by mdedetrich** [comment]
> @mdedetrich So why the compiler did not prevent this but produced an artifact?

It should have prevented this, and at least for Scala 3 there is a discussion to detect this and make the compiler produce a warning (see https://github.com/lampepfl/dotty/issues/18227#issuecomment-1638352282).

This not being there was an oversight

**Comment by nicolasstucki** [comment]
A linting option will be added to detect these issues: https://github.com/lampepfl/dotty/issues/18234
