### ISSUE TITLE
Update Git rules to follow work pattern.

### ISSUE THREAD

**Issue by Claudenw** [apache/incubator-pekko#51]
The github rules should not allow merging of pull requests when there are 

1. open changes requested.
2. ongoing conversations (not resolved conversations).

I am not certain how to configure this on the Apache git system.

**Comment by Claudenw** [comment]
pj assigning to you because you seem to have the experience in this realm.

**Comment by pjfanning** [comment]
The documented features are at https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features - I'll look later to see if I can spot something that we can use

**Comment by mdedetrich** [comment]
Especially with point 2, this to me I think this is too strict. I have been in cases where pull requests stuck open in perpetuity because someone forgets to click the "resolve" button. Either that or committers will just blindly hit resolve which at that point defeats the purpose of it.

Should we discuss in the mailing list? I think for now this is fine, we can always add stricter checks later if there is a consensus on it.

**Comment by sam-byng** [comment]
@mdedetrich seems like we've got a resolution on this now, with the mandatory single reviewer . Could this be closed?
