### ISSUE TITLE
Need to put LICENSE and NOTICE file in every pekko jar META-INF/ dir

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko#74]
If you look at any ASF jar, you will find these 2 files.

**Comment by spangaer** [comment]
Any known ASF SBT built projects? (hence prior art)

**Comment by pjfanning** [comment]
I did a quick search around Apache projects and didn't find any using sbt. I'm sure other projects use sbt, just not the obvious Scala ones like Spark, Kafka, Linkis, Sedona, Flink.

**Comment by spangaer** [comment]
Bummer.

If this hasn't moved by second half of January, I might have stab at it. When the project started I already thought this was a wonderfully boring task, that someone would have to do eventually 😋 

If someone else want to take it up before, I really don't mind 😉 . No dibs here, I just won't get to it sooner.


Unless it should just be a copy of the files sitting at the repo root? Because in that case 2 symlinks can do wonders. 🤷

**Comment by pjfanning** [comment]
#77 is merged
